CREATE DATABASE IF NOT EXISTS user_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS product_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS order_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;
